# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NaiveBayesTweets_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(635, 564)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 593, 447))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.radioButtonEntrenamienotPrevio = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonEntrenamienotPrevio.setGeometry(QtCore.QRect(9, 9, 174, 23))
        self.radioButtonEntrenamienotPrevio.setObjectName("radioButtonEntrenamienotPrevio")
        self.radioButtonEntrenamientoNuevo = QtWidgets.QRadioButton(self.scrollAreaWidgetContents)
        self.radioButtonEntrenamientoNuevo.setGeometry(QtCore.QRect(10, 110, 191, 23))
        self.radioButtonEntrenamientoNuevo.setObjectName("radioButtonEntrenamientoNuevo")
        self.plainTextEditPrevio = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEditPrevio.setGeometry(QtCore.QRect(9, 38, 471, 31))
        self.plainTextEditPrevio.setPlainText("")
        self.plainTextEditPrevio.setObjectName("plainTextEditPrevio")
        self.pushButtonEntrenamientoPrevio = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonEntrenamientoPrevio.setGeometry(QtCore.QRect(490, 40, 89, 25))
        self.pushButtonEntrenamientoPrevio.setObjectName("pushButtonEntrenamientoPrevio")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(40, 140, 151, 17))
        self.label_4.setObjectName("label_4")
        self.plainTextEditTrain = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEditTrain.setGeometry(QtCore.QRect(40, 160, 441, 31))
        self.plainTextEditTrain.setObjectName("plainTextEditTrain")
        self.pushButtonTrainFile = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonTrainFile.setGeometry(QtCore.QRect(490, 160, 89, 25))
        self.pushButtonTrainFile.setObjectName("pushButtonTrainFile")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 111, 17))
        self.label_5.setObjectName("label_5")
        self.plainTextEditTest = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.plainTextEditTest.setGeometry(QtCore.QRect(40, 230, 441, 31))
        self.plainTextEditTest.setObjectName("plainTextEditTest")
        self.pushButtonTesFile = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonTesFile.setGeometry(QtCore.QRect(490, 230, 89, 25))
        self.pushButtonTesFile.setObjectName("pushButtonTesFile")
        self.pushButtonEntrenar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonEntrenar.setGeometry(QtCore.QRect(50, 280, 89, 25))
        self.pushButtonEntrenar.setObjectName("pushButtonEntrenar")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(40, 330, 241, 21))
        self.label_3.setObjectName("label_3")
        self.label_resTrain = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_resTrain.setGeometry(QtCore.QRect(40, 360, 501, 21))
        self.label_resTrain.setText("")
        self.label_resTrain.setObjectName("label_resTrain")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 593, 447))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.label_2.setObjectName("label_2")
        self.plainTextEditTweet = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents_2)
        self.plainTextEditTweet.setGeometry(QtCore.QRect(10, 70, 561, 101))
        self.plainTextEditTweet.setObjectName("plainTextEditTweet")
        self.pushButtonClasificar = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonClasificar.setGeometry(QtCore.QRect(90, 200, 411, 31))
        self.pushButtonClasificar.setObjectName("pushButtonClasificar")
        self.labelResultado = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.labelResultado.setGeometry(QtCore.QRect(20, 260, 521, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.labelResultado.setFont(font)
        self.labelResultado.setObjectName("labelResultado")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CLASIFICADOR BAYESIANO INGENUO  DE TWEETS DE TURISMO"))
        self.radioButtonEntrenamienotPrevio.setText(_translate("MainWindow", "Entrenamiento previo"))
        self.radioButtonEntrenamientoNuevo.setText(_translate("MainWindow", "Entrenammiento nuevo"))
        self.pushButtonEntrenamientoPrevio.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Archivo para entrenar"))
        self.pushButtonTrainFile.setText(_translate("MainWindow", "Browse"))
        self.label_5.setText(_translate("MainWindow", "Archivo de test"))
        self.pushButtonTesFile.setText(_translate("MainWindow", "Browse"))
        self.pushButtonEntrenar.setText(_translate("MainWindow", "Entrenar"))
        self.label_3.setText(_translate("MainWindow", "Resultado del entrenamiento"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Entrenamiento"))
        self.label_2.setText(_translate("MainWindow", "Tweet a clasificar"))
        self.pushButtonClasificar.setText(_translate("MainWindow", "Clasificar"))
        self.labelResultado.setText(_translate("MainWindow", "Clasificación: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Clasificar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
